network:
  # default network passphrase
  passphrase: "Public Brave Stellar Network ; April 2018"
  # horizon server url
  horizon: "http://127.0.0.1:8000"

account:
  root: GBADF6QQKKMM7A5N26VXJQGBYTXPWMURJVUXZ4VEHIROJJS2Q22ONK3E
  uncle: GAQMCPSHBREWQEUGGLSRTMGENQ6E6AIV4B7HB6KGBSUJCKYDQXIG3LAD
  # SA2HJJJFXGT3W2YFD5D3ARCAP5XV7RFBHS7FSSOCMSAG6UICLWNEEFBW
  bob: GBWGODG5WLEH2BKRIQCLGMDOARCAVFI6KEKM7BKZL7EEXNBQMZOAP7ML
  # SBCJYEB4OOAIAEX6ZQOV3VJ6YPVDF2WAAGXVHUD6L64GUZIUDE2SZYBE
  jin: GCDLMIBCNNAR7S42XFSKAWWIUYM4RWKEJYQBQ6MO6WSP5QNQLSRO2ASL
  # SBAZXBPX46HHHJFCZNAL5PS3FTFOKIVMMBDPBPOOFURCVSFRIBGQ2TNE
